"""password reset tokens and a session cutoff

`password_resets` holds sha256 hashes rather than the tokens themselves: the
raw value is a bearer credential that exists once, in an email, and a database
leak must not also hand over working reset links.

`users.token_version` is how a completed reset ends the sessions the old
password could have started. Refresh tokens are stateless JWTs with no store to
revoke from, so the version lives on the user, every token carries the value it
was minted under, and a mismatch is a 401. A counter rather than a timestamp
because `iat` is whole seconds: a time-based cutoff either spares tokens minted
in the same second as the reset, or refuses the pair the reset itself returns.

Revision ID: 82187d5b98a5
Revises: 0129e065904c
Create Date: 2026-09-15 14:21:16.702302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82187d5b98a5'
down_revision: Union[str, Sequence[str], None] = '0129e065904c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False,
                                     server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
